#database
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://local:3306/dating?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.dating.domain